/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;


import java.awt.event.ActionEvent;
import java.time.LocalDateTime;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author Олег
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        new Timer(1000, (ActionEvent e) -> {
            LocalDateTime ldt = LocalDateTime.now();
            jHr.setText(String.valueOf(ldt.getHour())+":"+String.valueOf(ldt.getMinute())+":"+String.valueOf(ldt.getSecond()));
        }).start();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jStart = new javax.swing.JLabel();
        jSetting = new javax.swing.JLabel();
        jHr = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Bomber.png"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Bomber_2.png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jStart.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jStart.setForeground(new java.awt.Color(255, 255, 255));
        jStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jStart.setText("START");
        jStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jStartMouseClicked(evt);
            }
        });
        jPanel2.add(jStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 110, 50));

        jSetting.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jSetting.setForeground(new java.awt.Color(255, 255, 255));
        jSetting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jSetting.setText("SETTINGS");
        jSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSettingMouseClicked(evt);
            }
        });
        jPanel2.add(jSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 170, 50));

        jHr.setBackground(new java.awt.Color(0, 0, 0));
        jHr.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        jHr.setForeground(new java.awt.Color(204, 0, 0));
        jHr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHr.setText("00:00:00");
        jPanel2.add(jHr, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 100, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("by Oleg Boychuk");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 450, 100, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bomb.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 400, 150));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_Close.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/background_main.jpg"))); // NOI18N
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel5MouseDragged(evt);
            }
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 470));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void attenuation(int time){
        float z = 0.1f;
            for(int i = 1;i<10;i++){
                    frame.setOpacity(1.0f-z);
                    z+=0.1f;
            try {
                TimeUnit.MILLISECONDS.sleep(time);
            } catch (InterruptedException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
        frame.setVisible(false);
        this.setLocationRelativeTo(null);
        frame.setOpacity(1.0f);
    }
    private void jStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jStartMouseClicked
        attenuation(20);
        GameMain1.getGameMain().muss(sett.getSetting().getHei(),100);
        GameMain1.getGameMain().setVisible(true);
    }//GEN-LAST:event_jStartMouseClicked
    
    private void jSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSettingMouseClicked
        attenuation(20);
        sett.getSetting().setVisible(true);
    }//GEN-LAST:event_jSettingMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        attenuation(35);
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
        frame.setOpacity(0.5f);
    }//GEN-LAST:event_jLabel5MouseDragged

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        float z = 0.1f;
            for(int i = 1;i<=5;i++){
                try {
                    frame.setOpacity(z+0.5f);
                    z+=0.1f;
                    TimeUnit.MILLISECONDS.sleep(35);
                } catch (InterruptedException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_jLabel5MouseReleased
    int xx,xy;
    /**
     * @param args the command line arguments
     */
    static NewJFrame frame =  new NewJFrame();
    static Setting sett = new Setting();
    public static GameMain1 game = new GameMain1();
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            frame.setVisible(true);
        });
    }
    public static NewJFrame getFrame() {
		return frame;
	}

	public static Setting getSett() {
		return sett;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jHr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jSetting;
    private javax.swing.JLabel jStart;
    // End of variables declaration//GEN-END:variables



}
