/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import gui.GuiAction;
import gui.GuiCell;

/**
 *
 * @author Олег
 */

public class Setting extends javax.swing.JFrame {
    /**Setting
     * Creates new form Setting
     */
    NewJFrame ddd = new NewJFrame();
    
    public Setting() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jchoise1 = new javax.swing.JLabel();
        jchoise2 = new javax.swing.JLabel();
        jchoise3 = new javax.swing.JLabel();
        jchoise4 = new javax.swing.JLabel();
        jPromo3 = new javax.swing.JLabel();
        jPromo1 = new javax.swing.JLabel();
        jPromo2 = new javax.swing.JLabel();
        jPromo4 = new javax.swing.JLabel();
        jPromo5 = new javax.swing.JLabel();
        Backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_Close.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SETTINGS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 220, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_Back.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 50));

        jchoise1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        jchoise1.setForeground(new java.awt.Color(47, 192, 16));
        jchoise1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jchoise1.setText("10x10");
        jchoise1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jchoise1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jchoise1MouseClicked(evt);
            }
        });
        jPanel1.add(jchoise1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 180, 140, 110));

        jchoise2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        jchoise2.setForeground(new java.awt.Color(255, 255, 255));
        jchoise2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jchoise2.setText("15x12");
        jchoise2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jchoise2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jchoise2MouseClicked(evt);
            }
        });
        jPanel1.add(jchoise2, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 180, 140, 110));

        jchoise3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        jchoise3.setForeground(new java.awt.Color(255, 255, 255));
        jchoise3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jchoise3.setText("25x25");
        jchoise3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jchoise3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jchoise3MouseClicked(evt);
            }
        });
        jPanel1.add(jchoise3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 140, 110));

        jchoise4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        jchoise4.setForeground(new java.awt.Color(255, 255, 255));
        jchoise4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jchoise4.setText("40x25");
        jchoise4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jchoise4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jchoise4MouseClicked(evt);
            }
        });
        jPanel1.add(jchoise4, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 180, 140, 110));

        jPromo3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jPromo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPromo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/promo3.png"))); // NOI18N
        jPromo3.setText("WHITE");
        jPromo3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPromo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPromo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPromo3MouseClicked(evt);
            }
        });
        jPanel1.add(jPromo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 90, 90));

        jPromo1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jPromo1.setForeground(new java.awt.Color(51, 255, 51));
        jPromo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPromo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/promo1.png"))); // NOI18N
        jPromo1.setText("GRAY");
        jPromo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPromo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPromo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPromo1MouseClicked(evt);
            }
        });
        jPanel1.add(jPromo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 90, 90));

        jPromo2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jPromo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPromo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/promo2.png"))); // NOI18N
        jPromo2.setText("BLUE");
        jPromo2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPromo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPromo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPromo2MouseClicked(evt);
            }
        });
        jPanel1.add(jPromo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 90, 90));

        jPromo4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jPromo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPromo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/promo4.png"))); // NOI18N
        jPromo4.setText("CLASIC");
        jPromo4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPromo4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPromo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPromo4MouseClicked(evt);
            }
        });
        jPanel1.add(jPromo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 430, 90, 90));

        jPromo5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jPromo5.setForeground(new java.awt.Color(204, 204, 204));
        jPromo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPromo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/promo5.png"))); // NOI18N
        jPromo5.setText("ULTRA");
        jPromo5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPromo5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPromo5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPromo5MouseClicked(evt);
            }
        });
        jPanel1.add(jPromo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 90, 90));

        Backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/background_settings.jpg"))); // NOI18N
        Backround.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BackroundMouseDragged(evt);
            }
        });
        Backround.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackroundMousePressed(evt);
            }
        });
        jPanel1.add(Backround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked
 int xx,xy;
    private void BackroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackroundMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_BackroundMousePressed

    private void BackroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackroundMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_BackroundMouseDragged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        sett.setVisible(false);
        this.setLocationRelativeTo(null);
        frame.getFrame().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked
public int heigh=338;
public int getHei(){
    return heigh;
}
public void setHei(int hei){
    heigh = hei;
}
public String folder = "gray/";

    private void jchoise1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchoise1MouseClicked
        jchoise1.setForeground(new java.awt.Color(47, 192, 16));
        jchoise2.setForeground(new java.awt.Color(255, 255, 255));
        jchoise3.setForeground(new java.awt.Color(255, 255, 255));
        jchoise4.setForeground(new java.awt.Color(255, 255, 255));
        GuiCell.PATH="/icons/"+folder+"lar/";
        GuiCell.PADDING = 41;
        GuiAction.setRESOLUTION_X(10);
        GuiAction.setRESOLUTION_Y(10);
        GuiAction.setNUM_BOMBS(2);
        int x =GuiAction.RESOLUTION_X*GuiCell.PADDING;
        int y =GuiAction.RESOLUTION_Y*GuiCell.PADDING;
        NewJFrame.game.setX(x);
        NewJFrame.game.setY(y);
        setHei(338);
    }//GEN-LAST:event_jchoise1MouseClicked

    private void jchoise2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchoise2MouseClicked
       jchoise2.setForeground(new java.awt.Color(244, 245, 43));
       jchoise1.setForeground(new java.awt.Color(255, 255, 255));
        jchoise3.setForeground(new java.awt.Color(255, 255, 255));
        jchoise4.setForeground(new java.awt.Color(255, 255, 255));
        GuiCell.PATH="/icons/"+folder+"lar/";
                GuiCell.PADDING=41;
                GuiAction.setRESOLUTION_X(15);
                GuiAction.setRESOLUTION_Y(12);
                GuiAction.setNUM_BOMBS(60);
                int x =GuiAction.RESOLUTION_X*GuiCell.PADDING;
                int y =GuiAction.RESOLUTION_Y*GuiCell.PADDING;
                NewJFrame.game.setX(x);
                NewJFrame.game.setY(y);
                setHei(235);
    }//GEN-LAST:event_jchoise2MouseClicked

    private void jchoise3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchoise3MouseClicked
        jchoise3.setForeground(new java.awt.Color(250, 147, 0));
        jchoise2.setForeground(new java.awt.Color(255, 255, 255));
        jchoise1.setForeground(new java.awt.Color(255, 255, 255));
        jchoise4.setForeground(new java.awt.Color(255, 255, 255));
        GuiCell.PATH="/icons/"+folder;
                GuiCell.PADDING=20;
                GuiAction.setRESOLUTION_X(25);
                GuiAction.setRESOLUTION_Y(25);
                GuiAction.setNUM_BOMBS(150);
                int x =GuiAction.RESOLUTION_X*GuiCell.PADDING;
                int y =GuiAction.RESOLUTION_Y*GuiCell.PADDING;
                NewJFrame.game.setX(x);
                NewJFrame.game.setY(y);
                setHei(293);
    }//GEN-LAST:event_jchoise3MouseClicked

    private void jchoise4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchoise4MouseClicked
        jchoise4.setForeground(new java.awt.Color(255, 0, 0));
        jchoise2.setForeground(new java.awt.Color(255, 255, 255));
        jchoise3.setForeground(new java.awt.Color(255, 255, 255));
        jchoise1.setForeground(new java.awt.Color(255, 255, 255));
        GuiCell.PATH="/icons/"+folder;
                GuiCell.PADDING=20;
                GuiAction.setRESOLUTION_X(45);
                GuiAction.setRESOLUTION_Y(25);
                GuiAction.setNUM_BOMBS(250);
                int x =GuiAction.RESOLUTION_X*GuiCell.PADDING;
                int y =GuiAction.RESOLUTION_Y*GuiCell.PADDING;
                NewJFrame.game.setX(x);
                NewJFrame.game.setY(y);
                setHei(93);
    }//GEN-LAST:event_jchoise4MouseClicked

    private void jPromo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPromo3MouseClicked
        jPromo3.setForeground(new java.awt.Color(51, 255, 51));
        jPromo1.setForeground(new java.awt.Color(0, 0, 0));
        jPromo2.setForeground(new java.awt.Color(0, 0, 0));
        jPromo4.setForeground(new java.awt.Color(0, 0, 0));
        jPromo5.setForeground(new java.awt.Color(204, 204, 204));
        folder = "white/";
    }//GEN-LAST:event_jPromo3MouseClicked

    private void jPromo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPromo1MouseClicked
        jPromo1.setForeground(new java.awt.Color(51, 255, 51));
        jPromo3.setForeground(new java.awt.Color(0, 0, 0));
        jPromo2.setForeground(new java.awt.Color(0, 0, 0));
        jPromo4.setForeground(new java.awt.Color(0, 0, 0));
        jPromo5.setForeground(new java.awt.Color(204, 204, 204));
        folder = "gray/";
    }//GEN-LAST:event_jPromo1MouseClicked

    private void jPromo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPromo2MouseClicked
        jPromo2.setForeground(new java.awt.Color(51, 255, 51));
        jPromo1.setForeground(new java.awt.Color(0, 0, 0));
        jPromo3.setForeground(new java.awt.Color(0, 0, 0));
        jPromo4.setForeground(new java.awt.Color(0, 0, 0));
        jPromo5.setForeground(new java.awt.Color(204, 204, 204));
        folder = "blue/";
    }//GEN-LAST:event_jPromo2MouseClicked

    private void jPromo4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPromo4MouseClicked
       jPromo4.setForeground(new java.awt.Color(51, 255, 51));
        jPromo1.setForeground(new java.awt.Color(0, 0, 0));
       jPromo2.setForeground(new java.awt.Color(0, 0, 0));
        jPromo3.setForeground(new java.awt.Color(0, 0, 0));
         jPromo5.setForeground(new java.awt.Color(204, 204, 204));
        folder = "clasic/";
    }//GEN-LAST:event_jPromo4MouseClicked

    private void jPromo5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPromo5MouseClicked
        jPromo5.setForeground(new java.awt.Color(51, 255, 51));
        jPromo1.setForeground(new java.awt.Color(0, 0, 0));
        jPromo2.setForeground(new java.awt.Color(0, 0, 0));
        jPromo3.setForeground(new java.awt.Color(0, 0, 0));
        jPromo4.setForeground(new java.awt.Color(0, 0, 0));
        folder = "ultra/";
    }//GEN-LAST:event_jPromo5MouseClicked

    /**
     * @param args the command line arguments
     */
    static NewJFrame frame =  new NewJFrame();
    static Setting sett = new Setting();
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                sett.setVisible(true);
            }
        });
    }
    public Setting getSetting(){
        return sett;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backround;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPromo1;
    private javax.swing.JLabel jPromo2;
    private javax.swing.JLabel jPromo3;
    private javax.swing.JLabel jPromo4;
    private javax.swing.JLabel jPromo5;
    public javax.swing.JLabel jchoise1;
    public javax.swing.JLabel jchoise2;
    public javax.swing.JLabel jchoise3;
    public javax.swing.JLabel jchoise4;
    // End of variables declaration//GEN-END:variables
}
